build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: true

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

console-reports:
  active: true

complexity:
  ComplexMethod:
    threshold: 40
  NestedBlockDepth:
    threshold: 5

style:
  ReturnCount:
    max: 5
  WildcardImport:
    excludeImports:
      - 'java.io.*'
      - 'kotlin.test.*'
      - 'ru.hse.ezh.execution.commands.*'
