name: Publish-Dokka-documentation
on:
  push:
    branches:
      - hw2-ezh-impl
      - hw3-ezh-subst-pipe-impl
      - hw4-grep
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          cache: gradle
      - run: chmod +x gradlew
      - name: Build documentation
        run: ./gradlew dokkaHtml
      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: ./build/dokka/html
